### ISSUE TITLE
Implement image spec

### ISSUE THREAD

**Issue by harche** [containers/containrs#20]
runtime spec has already been written by kata, https://github.com/kata-containers/kata-containers/blob/2.0-dev/src/agent/oci/src/lib.rs#L31 (kata agent 2.0) , but there is no image spec yet. 

This issue is to track the progress of writing an image spec in rust.

**Comment by harche** [comment]
https://github.com/smiyaguchi/oci-spec too only implements runtime-spec so far.

**Comment by harche** [comment]
reserved the crate name, https://crates.io/crates/image-spec

**Comment by saschagrunert** [comment]
In the same manner as for https://github.com/cri-o/cri/issues/22, it may be a good idea to switch to a workspace of crates inside this project to maintain them inside one repository. :)

**Comment by saschagrunert** [comment]
This is already done in the oci-spec-rs crate.
